"""Revise adminunits to long style

Revision ID: 057abcd1b25a
Revises: 3e695d3babdb
Create Date: 2024-02-27 19:21:04.277264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '057abcd1b25a'
down_revision = '3e695d3babdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_units', sa.Column('pcode', sa.String(length=20), nullable=False))
    op.add_column('admin_units', sa.Column('admin_level', sa.SMALLINT(), nullable=False))
    op.add_column('admin_units', sa.Column('name_en', sa.String(length=255), nullable=False))
    op.add_column('admin_units', sa.Column('name_lan2', sa.String(length=255), nullable=True))
    op.add_column('admin_units', sa.Column('name_lan3', sa.String(length=255), nullable=True))
    op.add_column('admin_units', sa.Column('parent_pcode', sa.String(length=20), nullable=True))
    op.add_column('admin_units', sa.Column('valid_from', sa.Date(), nullable=True))
    op.drop_column('admin_units', 'id')
    op.drop_column('admin_units', 'adm1_lan2')
    op.drop_column('admin_units', 'pcode_3')
    op.drop_column('admin_units', 'pcode_0')
    op.drop_column('admin_units', 'adm3_lan2')
    op.drop_column('admin_units', 'adm2_en')
    op.drop_column('admin_units', 'pcode_1')
    op.drop_column('admin_units', 'adm1_lan3')
    op.drop_column('admin_units', 'adm0_lan3')
    op.drop_column('admin_units', 'pcode_2')
    op.drop_column('admin_units', 'adm3_lan3')
    op.drop_column('admin_units', 'adm2_lan2')
    op.drop_column('admin_units', 'adm0_lan2')
    op.drop_column('admin_units', 'adm2_lan3')
    op.drop_column('admin_units', 'adm0_en')
    op.drop_column('admin_units', 'adm3_en')
    op.drop_column('admin_units', 'adm1_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_units', sa.Column('adm1_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('adm3_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('adm0_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('admin_units', sa.Column('adm2_lan3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('adm0_lan2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('adm2_lan2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('adm3_lan3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('pcode_2', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('adm0_lan3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('adm1_lan3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('pcode_1', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('adm2_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('adm3_lan2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('pcode_0', postgresql.ENUM('AW', 'AF', 'AO', 'AI', 'AX', 'AL', 'AD', 'AE', 'AR', 'AM', 'AS', 'AQ', 'TF', 'AG', 'AU', 'AT', 'AZ', 'BI', 'BE', 'BJ', 'BQ', 'BF', 'BD', 'BG', 'BH', 'BS', 'BA', 'BL', 'BY', 'BZ', 'BM', 'BO', 'BR', 'BB', 'BN', 'BT', 'BV', 'BW', 'CF', 'CA', 'CC', 'CH', 'CL', 'CN', 'CI', 'CM', 'CD', 'CG', 'CK', 'CO', 'KM', 'CV', 'CR', 'CU', 'CW', 'CX', 'KY', 'CY', 'CZ', 'DE', 'DJ', 'DM', 'DK', 'DO', 'DZ', 'EC', 'EG', 'ER', 'EH', 'ES', 'EE', 'ET', 'FI', 'FJ', 'FK', 'FR', 'FO', 'FM', 'GA', 'GB', 'GE', 'GG', 'GH', 'GI', 'GN', 'GP', 'GM', 'GW', 'GQ', 'GR', 'GD', 'GL', 'GT', 'GF', 'GU', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'ID', 'IM', 'IN', 'IO', 'IE', 'IR', 'IQ', 'IS', 'IL', 'IT', 'JM', 'JE', 'JO', 'JP', 'KZ', 'KE', 'KG', 'KH', 'KI', 'KN', 'KR', 'KW', 'LA', 'LB', 'LR', 'LY', 'LC', 'LI', 'LK', 'LS', 'LT', 'LU', 'LV', 'MO', 'MF', 'MA', 'MC', 'MD', 'MG', 'MV', 'MX', 'MH', 'MK', 'ML', 'MT', 'MM', 'ME', 'MN', 'MP', 'MZ', 'MR', 'MS', 'MQ', 'MU', 'MW', 'MY', 'YT', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NU', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PK', 'PA', 'PN', 'PE', 'PH', 'PW', 'PG', 'PL', 'PR', 'KP', 'PT', 'PY', 'PS', 'PF', 'QA', 'RE', 'RO', 'RU', 'RW', 'SA', 'SD', 'SN', 'SG', 'GS', 'SH', 'SJ', 'SB', 'SL', 'SV', 'SM', 'SO', 'PM', 'RS', 'SS', 'ST', 'SR', 'SK', 'SI', 'SE', 'SZ', 'SX', 'SC', 'SY', 'TC', 'TD', 'TG', 'TH', 'TJ', 'TK', 'TM', 'TL', 'TO', 'TT', 'TN', 'TR', 'TV', 'TW', 'TZ', 'UG', 'UA', 'UM', 'UY', 'US', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'ZA', 'ZM', 'ZW', name='countriesenum2'), autoincrement=False, nullable=False))
    op.add_column('admin_units', sa.Column('pcode_3', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('adm1_lan2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('admin_units', 'valid_from')
    op.drop_column('admin_units', 'parent_pcode')
    op.drop_column('admin_units', 'name_lan3')
    op.drop_column('admin_units', 'name_lan2')
    op.drop_column('admin_units', 'name_en')
    op.drop_column('admin_units', 'admin_level')
    op.drop_column('admin_units', 'pcode')
    # ### end Alembic commands ###
