"""Increase prob precision

Revision ID: 0e7340e57301
Revises: e67f64ad2817
Create Date: 2024-03-17 14:41:41.360969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7340e57301'
down_revision = 'e67f64ad2817'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('migration', 'proportion',
                    existing_type=sa.Numeric(precision=5, scale=4),
                    type_=sa.Numeric(precision=5, scale=2),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('migration', 'proportion',
                    existing_type=sa.Numeric(precision=5, scale=2),
                    type_=sa.Numeric(precision=5, scale=4),
                    existing_nullable=False)
    # ### end Alembic commands ###
