"""Add tables

Revision ID: 0fb6cc8a4783
Revises: 0457ba593183
Create Date: 2024-02-24 19:35:04.162016

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '0fb6cc8a4783'
down_revision = '0457ba593183'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    op.create_table('admin_units',
        sa.Column('pcode', sa.String(length=20), primary_key=True, nullable=False),
        sa.Column('admin_level', sa.SMALLINT(), nullable=False),
        sa.Column('country', sa.String(length=3), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('parent_pcode', sa.String(length=20), nullable=True),
        sa.Column('valid_from', sa.Date(), nullable=False),
        sa.Column('geometry', geoalchemy2.Geometry(
            geometry_type='MULTIPOLYGON',
            srid=4326,
            name='geometry'
        ), nullable=False)
    )
    op.create_table('migration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('admin_level', sa.SMALLINT(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=20), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('age_min', sa.SMALLINT(), nullable=False),
    sa.Column('age_max', sa.SMALLINT(), nullable=False),
    sa.Column('sex', sa.SMALLINT(), nullable=False),
    sa.Column('probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('population',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('admin_level', sa.SMALLINT(), nullable=False),
    sa.Column('pcode', sa.String(length=20), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('age_min', sa.SMALLINT(), nullable=False),
    sa.Column('age_max', sa.SMALLINT(), nullable=False),
    sa.Column('sex', sa.SMALLINT(), nullable=False),
    sa.Column('pop', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pop_upper', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pop_lower', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pop_quartiles', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['pcode'], ['admin_units.pcode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_population_day'), 'population', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_population_day'), table_name='population')
    op.drop_table('population')
    op.drop_table('migration')
    op.drop_table('admin_units')
    # ### end Alembic commands ###
