"""Add country languages

Revision ID: 212b51c4d61b
Revises: 64ff48df3973
Create Date: 2024-02-27 19:45:38.664491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212b51c4d61b'
down_revision = '64ff48df3973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_units', sa.Column('country_lan2', sa.String(length=255), nullable=True))
    op.add_column('admin_units', sa.Column('country_lan3', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_units', 'country_lan3')
    op.drop_column('admin_units', 'country_lan2')
    # ### end Alembic commands ###
