"""Create user table

Revision ID: 215dcdb2515f
Revises: 
Create Date: 2024-02-06 18:43:55.518733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215dcdb2515f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='userroleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
