"""remove unwanted fields

Revision ID: 64ff48df3973
Revises: 057abcd1b25a
Create Date: 2024-02-27 19:39:50.835891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ff48df3973'
down_revision = '057abcd1b25a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_units', 'valid_from')
    op.drop_column('admin_units', 'parent_pcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_units', sa.Column('parent_pcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('admin_units', sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
