"""Fix typo

Revision ID: e4e20b39850c
Revises: 6c00288d3c43
Create Date: 2024-02-25 16:14:39.975067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e20b39850c'
down_revision = '6c00288d3c43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_units', sa.Column('adm1_lan3', sa.String(length=255), nullable=True))
    op.drop_column('admin_units', 'adm_lan3')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_units', sa.Column('adm_lan3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('admin_units', 'adm1_lan3')
    # ### end Alembic commands ###
