"""alter pop and migration schema

Revision ID: e67f64ad2817
Revises: ff8497829bd1
Create Date: 2024-03-09 17:45:06.146662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e67f64ad2817'
down_revision = 'ff8497829bd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migration', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('population', sa.Column('pop_posterior', sa.ARRAY(sa.Integer()), nullable=False))
    op.drop_column('population', 'pop_quantiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('population', sa.Column('pop_quantiles', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_column('population', 'pop_posterior')
    op.drop_column('migration', 'count')
    # ### end Alembic commands ###
