"""Fix typo in field name

Revision ID: ff8497829bd1
Revises: 212b51c4d61b
Create Date: 2024-03-03 16:30:27.592855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff8497829bd1'
down_revision = '212b51c4d61b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('population', sa.Column('pop_quantiles', sa.ARRAY(sa.Integer()), nullable=False))
    op.drop_column('population', 'pop_quartiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('population', sa.Column('pop_quartiles', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_column('population', 'pop_quantiles')
    # ### end Alembic commands ###
