# Five files are created in 'out_dir' for output data, specifically:
# 1. "kyvstar_pop_observed.csv"   - The observed population data.
# 2. "kyvstar_flows_observed.csv" - The observed flows data.
# 3. "kyvstar_flows.csv"          - The simulated flow data.
# 4. "kyvstar_pop.csv"            - The simulated population data.
# 5. "kyvstar_transitions.csv"    - The transition data for the simulation.

# Steps to simulate the true population:
# 1. Population by age and sex at time t0 is calculated.
# 2. Transition probabilities are applied based on the population at time t0.
# 3. The population at time t is determined.
# 4. The flow at time t is calculated based on the population and transitions.

# Steps to simulate Kyivstar data:
# 1. Calculate the population detection probability by age and sex.
# 2. The detected population is estimated.
# 3. Observed population is generated by adding normally distributed noise to the detected population.
# 4. Calculate the flow detection probability by age and sex and destination
# 5. The detected flows are estimated.
# 6. Observed flows are generated by adding normally distributed noise to the detected flows.


library(tidyverse)
library(ggplot2)
library(matrixcalc)

set.seed(1789)

locations <- sort(c("Kyiv", "Lviv", "Odesa", "Kharkiv")) # 4 locations
age_groups <- c("0-17", "18-24", "25-34", "35-44", "45-54", "55-64", "65+") # 7 age groups
sex <- c("Female", "Male") # 2 categories
times <- seq(as.Date("2023-01-01"), by = "month", length.out = 12) # 12 time points

check <- F # print check on the console

# output directory
source(file.path(here::here(), "R_helpers/generic.R"))
out_dir <- file.path(out_dir, "simulation", "Kyivstar")
dir.create(out_dir, showWarnings = F, recursive = T)

#  True process model ----------------------------------------------------------

## Baseline population ----------------------------------------------------

baseline_pop <- expand.grid(
  time = as.Date("2023-01-01"),
  origin = locations, # 4 origins
  age = age_groups, # 7 age groups
  sex = sex # 2 sexes
) |>
  arrange(time, age, sex, origin)


baseline_pop$pop <- round(
  rnorm(nrow(baseline_pop), mean = 3000, sd = 50)
  *
    ifelse(baseline_pop$origin == "Kyiv", 1.2,
      ifelse(baseline_pop$origin == "Lviv", 0.9,
        ifelse(baseline_pop$origin == "Odesa", 0.7, 1)
      )
    )
    *
    ifelse(baseline_pop$age %in% c("0-17", "45-54", "55-64"), 1.3, 1)
)

ggplot(
  data = baseline_pop,
  mapping = aes(
    x = ifelse(baseline_pop$sex == "Male", yes = -pop, no = pop),
    y = age, fill = sex
  )
) +
  geom_col() +
  labs(x = "Population") +
  facet_wrap(. ~ origin)



## Transition probabilities -----------------------------------------------

# this create transition for one time step
create_transition <- function(dim = length(locations)) {
  matrix_prob <- round(matrix(runif(dim * dim), nrow = dim, ncol = dim), 3)
  for (i in 1:dim) {
    matrix_prob[i, i] <- matrix_prob[i, i] * 10
  }
  col_sums <- colSums(matrix_prob)

  for (i in 1:dim) {
    matrix_prob[, i] <- matrix_prob[, i] / col_sums[i]
  }
  return(matrix_prob)
}

transition <- bind_rows(replicate(length(age_groups) * length(sex), create_transition() |> as_tibble(), simplify = FALSE))
colnames(transition) <- sort(locations)

transition_data <- baseline_pop |>
  rename(destination = origin) |>
  arrange(time, age, sex, destination) |>
  bind_cols(transition)

pop_data <- transition_data |>
  group_by(age, sex) |>
  group_modify(~ {
    location_matrix <- as.matrix(.x[, locations, drop = FALSE])
    pop_vector <- .x$pop
    for (i in 1:length(times[-1])) {
      matrix_exp <- matrix.power(location_matrix, i)
      .x[[paste0("pop_", times[-1][i])]] <- matrix_exp %*% pop_vector |> as.vector()
    }
    return(.x)
  })

pop_data <- pop_data |>
  select(-all_of(locations)) |>
  pivot_longer(cols = starts_with("pop"), values_to = "pop", names_to = "date") |>
  rowwise() |>
  mutate(
    time = ifelse(date == "pop", time, str_remove(date, "pop_")) |> as.Date()
  ) |>
  select(-date)

totals <- pop_data |>
  group_by(age, sex, time) |>
  summarise(pop = sum(pop))

ggplot(pop_data, aes(x = time, y = pop)) +
  geom_line(aes(color = destination)) +
  facet_grid(age ~ sex) +
  geom_line(data = totals, aes(color = "total")) +
  theme_minimal()


## Flows ------------------------------------------------------------------

flows <- transition_data |>
  slice(rep(1:n(), time = length(times))) |>
  mutate(time = rep(times, each = nrow(transition_data))) |>
  arrange(time, age, sex, destination) |>
  select(-pop) |>
  left_join(
    pop_data |>
      group_by(time, age, sex) |>
      # gather in one column all the population values
      mutate(pop = paste(pop, collapse = ","))
  ) |>
  mutate(
    # convert back the 'pop' column into a list
    pop_values = str_split(pop, ",") %>% # Split the 'pop' column by commas
      map(as.numeric), # Convert each element into numeric

    # Multiply the values by the corresponding pop value for each row
    Kharkiv = Kharkiv * map_dbl(pop_values, ~ .x[1]),
    Kyiv = Kyiv * map_dbl(pop_values, ~ .x[2]),
    Lviv = Lviv * map_dbl(pop_values, ~ .x[3]),
    Odesa = Odesa * map_dbl(pop_values, ~ .x[4])
  ) |>
  select(-pop_values, -pop)


### checks

if (check) {
  check <- pop_data |>
    left_join(
      transition_data |>
        filter(destination == "Kharkiv") |>
        select(-destination, -time, -pop) |>
        pivot_longer(cols = all_of(locations), names_to = "destination", values_to = "prop_to_kharkiv")
    ) |>
    mutate(pop_from_kharkiv = pop * prop_to_kharkiv) |>
    group_by(age, sex, time) |>
    summarise(pop_from_kharkiv = sum(pop_from_kharkiv)) |>
    left_join(pop_data |> filter(destination == "Kharkiv") |> select(-destination))

  flows |>
    group_by(time, age, sex) |>
    summarise(across(locations, sum)) |>
    pivot_longer(cols = all_of(locations), names_to = "destination", values_to = "pop_check") |>
    left_join(pop_data)
}


# Observation model ------------------------------------------------------

# Population
# detection prob varying by age and sex but constant through time
pop_detection_prob <- pop_data |>
  distinct(age, sex) |>
  rowwise() |>
  mutate(
    prop = runif(1, 0.7, 0.9)
  )

# add observation error
pop_noise <- 5
observed_pop <- pop_data |>
  left_join(pop_detection_prob) |>
  rowwise() |>
  mutate(
    pop_detected = pop * prop,
    pop_observed = abs(rnorm(1, pop_detected, pop_noise))
  )

# Flows
# detection prob varying by destination, age and sex but constant through time
flow_detection_prob <- flows |>
  distinct(age, sex, destination) |>
  rowwise() |>
  mutate(
    prop = runif(1, 0.6, 0.8) # lower detection prob than pop
  ) |>
  group_by(age, sex) |>
  summarise(prop = paste(prop, collapse = ","))

# add observation error
flow_noise <- 5
observed_flows <- flows |>
  left_join(flow_detection_prob) |>
  # rowwise() |>
  mutate(
    prop_values = str_split(prop, ",") |> # Split the 'pop' column by commas
      map(as.numeric), # Convert each element into numeric

    # Multiply the values by the corresponding pop value for each row
    Kharkiv = Kharkiv * map_dbl(prop_values, ~ .x[1]),
    Kyiv = Kyiv * map_dbl(prop_values, ~ .x[2]),
    Lviv = Lviv * map_dbl(prop_values, ~ .x[3]),
    Odesa = Odesa * map_dbl(prop_values, ~ .x[4])
  ) |>
  select(-prop_values, -prop) |>
  rowwise() |>
  mutate(across(locations, ~ abs(rnorm(1, .x, flow_noise))))



# write output -----------------------------------------------------------

write_csv(observed_pop, file.path(out_dir, paste0("kyvstar_pop_observed.csv")))
write_csv(observed_flows, file.path(out_dir, paste0("kyvstar_flows_observed.csv")))
write_csv(flows, file.path(out_dir, paste0("kyvstar_flows.csv")))
write_csv(pop_data, file.path(out_dir, paste0("kyvstar_pop.csv")))
write_csv(transition_data, file.path(out_dir, paste0("kyvstar_transitions.csv")))
