---
title: "Visualise individual covariates"
author: "Edith"
date: "`r format(Sys.time(), '%d %m %Y')`"
format: 
  html:
    fig-width: 8
    fig-height: 4
    code-fold: true
    toc: true
    embed-resources: true
---

```{r, message=FALSE, warning=FALSE}
# Load necessary libraries
library(kableExtra)
source(here::here(file.path("src", "helpers", "R_helpers", "generic.R")))

cov_df <- read_csv(file.path(out_dir, "covariates", "final",  "ua_covariates_oblast.csv")) %>%
  mutate(scale_label = paste0(sum_stat, ", ", time_std, ", ", space_std))
cov_processing <- read_csv(file.path(out_dir, "covariates", "final",  "ua_covariates_oblast_description.csv")) %>%
  mutate(scale_label = paste0(sum_stat, ", ", time_std, ", ", space_std))
cov_desc <- read_csv(file.path(out_dir, "covariates",  "ua_covariates_list.csv")) 
master_index <- read_csv(file.path(out_dir, paste0(tolower(country), "_master_index.csv")))|>
  distinct(i_key, i_name, i, ADM1_PCODE, macroregion)
cov_df <- cov_df |> 
  left_join(master_index)
```
# List of covariates
```{r}
cov_desc|> 
  kbl(escape=F, format = "html") |> 
  kable_classic(full_width = F)%>%
  scroll_box(width = "100%")
```
# Processing method
```{r}
cov_processing |> distinct(scale_label,sum_stat, time_std, space_std)  |> 
              mutate(
                Meaning = case_when(
                  grepl('week', time_std) ~ 'Temporal outliers',
                  grepl('sum', sum_stat) ~ 'Duration outliers',
                                    grepl('all', time_std)~ 'Extreme outliers',
                  !is.na(space_std) ~ 'Spatial outliers'
                )
              ) |> 
            rename(
              "Std. method label<br>(sum_std, time_std, spatial_std)" = "scale_label",
              "Summary statistic" = "sum_stat",
              "Time window<br>for standardising" = "time_std",
              "Spatial window<br>for standardising" = "space_std"

            ) |> 
  kbl(escape=F, format = "html") |> 
  kable_classic(full_width = F)
  
```
# Covariate visualisation

```{r}
#| output: asis

for(cov in sort(unique(cov_df$covariate), decreasing = T)){
  cat(paste0("\n\n## ", cov, "\n\n"))
  
  for(m in unique(master_index$macroregion)){
    # m= 'East'
    g <- ggplot(cov_df |> filter(covariate==cov&macroregion==m) , aes(x = t, y = value_std, color = scale_label)) +
      geom_line() +
      facet_wrap(~i_name, scales = "free_y") +
      labs(
        title = paste(cov, '-' ,m ),
        x = "Time",
        y = "Standardised value",
        color = "(Sum_stat, Time, Spatial)"
      ) +
      theme_minimal()
    print(g)
  }
}
```


# Covariate standardised distribution

```{r}
#| output: asis

for(cov in sort(unique(cov_df$covariate), decreasing = T)){
  cat(paste0("\n\n## ", cov, "\n\n"))
  
    # m= 'East'
    g <- ggplot(cov_df |> filter(covariate==cov) , aes(x = value_std)) +
      geom_histogram(bins=50) +
      facet_wrap(~scale_label, scales = "free_x") +
      labs(
        title = paste(cov),
        x = "Time",
        y = "Standardised value",
        color = "(Sum_stat, Time, Spatial)"
      ) +
      theme_minimal()
    print(g)
  
}
```
